<?xml version = "1.0"?>

<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "lidar_radius" value = "0.05" />
    <xacro:property name = "lidar_length" value = "0.04" />

    <link name = "laser_link">
        <visual>
            <geometry>
                <cylinder radius = "0.05" length = "0.04"/>
            </geometry>
            <material name = "red"/>
        </visual>
    </link>
    <collision>
        <visual>
            <geometry>
                <cylinder radius = "0.05" length = "0.04"/>
            </geometry>
        </visual>
    </collision>
    <xacro:wheel_inertia m = "0.1" r = "${lidar_radius}" l = "${lidar_length}"
                         xyz = "0 0 0" rpy = "0 0 0" />

    <joint name = "base_lidar_joint" type = "fixed">
        <parent link = "base_link" />
        <child link = "laser_link" />
        <origin xyz = "0 0 ${base_height + (lidar_length / 2.0)}" rpy = "0 0 0" />
    </joint>

    <gazebo reference="laser_link">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>5.0</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>